keycloak+gravitee roles configuration
gravitee-io/gravitee-docs pull request #332
Opened 2021-02-01 20:03 UTC by patricio-dorantes

Added new section and images as suggested by @brasseld.

2021-05-27 08:32 UTC, phiz71 requested changes

2021-05-27 08:34 UTC, phiz71 commented
Hi @patricio-dorantes , thank you for your PR, and sorry for the delay 🙇🏻 .
I made some comments because sometimes it was hard for me to find the right screen to configure keycloak.

Could you also rebase your PR ?
Thanks a lot.

2021-07-29 05:15 UTC, patricio-dorantes commented
I thank you in advance for your patience. I'm not so git proficient (yet).

2021-07-29 06:38 UTC, phiz71 approved these changes

2021-07-29 06:39 UTC, phiz71 commented
Thank you @patricio-dorantes for your contribution !

2021-07-29 06:39 UTC, merged