Feat(kubernetes): documentation about kubernetes integration using th…
gravitee-io/gravitee-docs pull request #380
Opened 2021-03-16 20:53 UTC by leleueri

…e gravitee-gateway-services-kuberentes

Fixes gravitee-io/issues#5173
Fixes gravitee-io/gravitee-docs#379

2021-03-16 21:30 UTC, brasseld commented on pages/apim/3.x/kubernetes/apim-kubernetes-overview.adoc
> +APIM 3.7.0 introduces a kubernetes plugin for the Gateway allowing the deployement of APIs using https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom Resource
`allowing the deployment of APIs`

2021-03-16 21:30 UTC, brasseld commented on pages/apim/3.x/kubernetes/apim-kubernetes-overview.adoc
> +WARNING: This plugin is currentlty in Alpha version, the Api-Key policy isn't available for APIs deployed using this plugin.
This plugin is currently in Alpha version

2021-03-16 23:00 UTC, brasseld requested changes

2021-03-18 18:04 UTC, plsstephenson requested changes

2021-03-18 18:04 UTC, plsstephenson commented on pages/apim/3.x/kubernetes/apim-kubernetes-installation.adoc
> +* https://raw.githubusercontent.com/gravitee-io/gravitee-gateway/master/gravitee-gateway-services/gravitee-gateway-services-kubernetes/src/main/crds/gravitee-plugin-crd.yml[GraviteePlugins]
These links don't work

2021-03-19 08:34 UTC, leleueri commented on pages/apim/3.x/kubernetes/apim-kubernetes-installation.adoc
> +* https://raw.githubusercontent.com/gravitee-io/gravitee-gateway/master/gravitee-gateway-services/gravitee-gateway-services-kubernetes/src/main/crds/gravitee-plugin-crd.yml[GraviteePlugins]
Links are fixed.

2021-03-19 08:45 UTC, leleueri commented on pages/apim/3.x/kubernetes/apim-kubernetes-installation.adoc
> +* https://raw.githubusercontent.com/gravitee-io/gravitee-gateway/master/gravitee-gateway-services/gravitee-gateway-services-kubernetes/src/main/crds/gravitee-plugin-crd.yml[GraviteePlugins]
Links are fixed.

2021-03-19 09:10 UTC, merged