Issues/4903 cpu memory health probe
gravitee-io/gravitee-docs pull request #393
Opened 2021-03-25 09:42 UTC by ytvnr

Fixes https://github.com/gravitee-io/issues/issues/4903

Need to be merged after https://github.com/gravitee-io/issues/issues/5236

2021-04-06 17:30 UTC, phiz71 requested changes

2021-04-06 17:30 UTC, phiz71 commented on pages/node/partial/technical-api.adoc
> +    memory: 80
```suggestion
services:
  health:
    threshold:
      cpu: 80
      memory: 80
```

2021-04-07 05:41 UTC, phiz71 approved these changes

2021-06-04 08:20 UTC, gcusnieux approved these changes

2021-06-04 08:21 UTC, merged