doc: upgrade mongo-driver
gravitee-io/gravitee-docs pull request #458
Opened 2021-07-27 16:09 UTC by phiz71

update gravitee.yml default configuration for mongo database

gravitee-io/issues#3661

2021-07-28 14:24 UTC, gaetanmaisse reviewed
I think we should add something about the attributes that aren't handled anymore: 
https://github.com/gravitee-io/gravitee-api-management/blob/72e88c3b229aa7ed949989708e4711d51ea31b21/gravitee-apim-repository/gravitee-apim-repository-mongodb/src/main/java/io/gravitee/repository/mongodb/common/MongoFactory.java#L180

2021-07-29 06:13 UTC, gaetanmaisse approved these changes

2021-07-29 08:56 UTC, tiffanymarchi requested changes
Overall, very nicely done, Florent! I just have a couple minor edits. Thank you!  (●'◡'●)

2021-07-29 08:56 UTC, tiffanymarchi commented on pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-mongodb.adoc
> +    serverSelectionTimeout:     # mongodb server selection time out (default 1000)
Could we please change "time out" to "timeout" in the definition for all of these? :) 

## Socket settings
    connectTimeOut:             # mongodb connection timeout (default 1000)
    socketTimeout:              # mongodb socket timeout (default 1000)

2021-07-29 08:56 UTC, tiffanymarchi commented on pages/apim/3.x/installation-guide/configuration/repositories/installation-guide-repositories-mongodb.adoc
> +From version 3.10.0, Gravitee.io APIM uses the 4.1.2 version of the Java Driver. As a consequence, some settings are not available anymore.
Let's please change: "As a consequence, some settings are not available anymore."

To: Therefore, some settings are no longer available.

2021-07-29 09:59 UTC, tiffanymarchi approved these changes

2021-07-29 09:59 UTC, merged