docs(apim): add notes about reverse proxy
gravitee-io/gravitee-docs pull request #661
Opened 2022-01-24 19:20 UTC by gcusnieux

2022-01-24 20:38 UTC, phiz71 requested changes
Is there a reason to have an empty file in this commit ?

2022-01-25 06:57 UTC, gcusnieux commented on _data/sidebars/apim_3_x_sidebar.yml
> +            url: /apim/3.x/apim_how_to_configure_reverse_proxy.html
I didn't put it there because the other How To are functional and the reverse-proxy configuration is more related to installation

2022-01-26 21:25 UTC, gcusnieux commented
> Is there a reason to have an empty file in this commit ?

No, I deleted this empty file

2022-01-26 21:29 UTC, phiz71 commented
You can merge your PR to master since this doc is relevant for the current version. No need to wait for a release for that.

2022-01-27 15:06 UTC, gcusnieux commented
> You can merge your PR to master since this doc is relevant for the current version. No need to wait for a release for that.

done @phiz71

2022-01-31 09:32 UTC, siongravitee approved these changes

2022-02-09 07:56 UTC, merged