fix(apim): update import documentation of api plans
gravitee-io/gravitee-docs pull request #751
Opened 2022-04-11 12:19 UTC by gcusnieux

gravitee-io/issues#7443

2022-04-12 08:49 UTC, a-cordier commented on pages/apim/3.x/user-guide/publisher/partial-update-apis.adoc
> +In case the condition fails the api will return an `HTTP 204 No Content`.
```suggestion
In case the condition fails the API will return an `HTTP 204 No Content`.
```

2022-04-12 08:50 UTC, a-cordier commented
as an addition to the examples maybe we could borrow from the K8S documentation and add some kind of syntax reference ?

I'm thinking about the table in this page https://kubernetes.io/docs/reference/kubectl/jsonpath/

2022-04-12 11:39 UTC, mouligno commented on pages/apim/3.x/user-guide/publisher/import-apis.adoc
> +* Plans in target API without subscriptions that are not present in the API definition will be _deleted_
```suggestion
* Plans in target API without subscriptions that are not present in the API definition will be _deleted_ (an error would be raised if plan got subscriptions)
```

2022-04-12 11:42 UTC, mouligno commented on pages/apim/3.x/user-guide/publisher/partial-update-apis.adoc
> +The replace operation updates the value at the target location with a new value.
```suggestion
The replace operation updates the value at the targeted location with a new value.
```

2022-04-12 11:42 UTC, mouligno commented on pages/apim/3.x/user-guide/publisher/partial-update-apis.adoc
> +Also, we can use it to insert a new item into an array.
```suggestion
It can be leverage to insert a new item into an array.
```

2022-04-12 11:43 UTC, mouligno commented on pages/apim/3.x/user-guide/publisher/partial-update-apis.adoc
> +The remove operation removes a value at the target location.
```suggestion
The remove operation removes a value at the targeted location.
```

2022-04-12 11:48 UTC, mouligno requested changes
LGTM, wanted your thoughts on the sentences

2022-04-13 06:17 UTC, gaetanmaisse commented
I think this PR should target the `apim_3.18` branch

2022-04-14 06:11 UTC, gcusnieux commented
Well done @allandenis38 & @mouligno ! It's really better 🚀

2022-04-26 06:55 UTC, mouligno approved these changes

2022-04-26 06:56 UTC, merged