docs: document security chain change in 3.10.19 upgrade note
gravitee-io/gravitee-docs pull request #836
Opened 2022-08-09 08:43 UTC by marcambier

**Issue**

https://github.com/gravitee-io/issues/issues/7824

2022-08-09 08:50 UTC, Okhelifi approved these changes

2022-08-09 08:57 UTC, ThibaudAV approved these changes

2022-08-09 09:21 UTC, phiz71 approved these changes

2022-08-11 09:05 UTC, ivan-gravitee requested changes
Some minor suggestions added

2022-08-11 09:05 UTC, ivan-gravitee commented on pages/apim/3.x/installation-guide/upgrades/3.10.19/README.adoc
> +That causes some behavior changes.
```suggestion
```

2022-08-11 09:05 UTC, ivan-gravitee commented on pages/apim/3.x/installation-guide/upgrades/3.10.19/README.adoc
> +Api keys and JWT plans are executed only if there is an active subscription related to the provided security token.
```suggestion
```

2022-08-11 09:05 UTC, ivan-gravitee commented on pages/apim/3.x/installation-guide/upgrades/3.10.19/README.adoc
> +If there is no relevant subscription, the plans won't be executed and security chain will continue the parse following plans.
```suggestion
```

2022-08-11 09:05 UTC, ivan-gravitee commented on pages/apim/3.x/installation-guide/upgrades/3.10.19/README.adoc
> +Here are some concrete examples of behavior changes :
```suggestion
Specific examples of this change are provided in the table below:
```

2022-08-11 09:05 UTC, ivan-gravitee commented on pages/apim/3.x/installation-guide/upgrades/3.10.19/README.adoc
> +|API plans | Request |Before this version |From this version
```suggestion
| API plans | Request | Prior to this version | From this version
```

2022-08-11 09:05 UTC, ivan-gravitee commented on pages/apim/3.x/installation-guide/upgrades/3.10.19/README.adoc
> +|Api key plan is executed = HTTP 401 unauthorized
```suggestion
|API key plan is executed = HTTP 401 unauthorized
```

2022-08-11 11:31 UTC, ivan-gravitee approved these changes
LGTM

2022-08-11 11:50 UTC, merged