docs(apim): add upgrade note for 3.15.17
gravitee-io/gravitee-docs pull request #845
Opened 2022-09-12 12:32 UTC by a-cordier

2022-09-12 13:16 UTC, marcambier approved these changes

2022-09-12 13:25 UTC, ivan-gravitee requested changes
Looks good - a couple of minor changes added

2022-09-22 07:10 UTC, ivan-gravitee approved these changes
LGTM

2022-11-09 05:08 UTC, ivan-gravitee commented
Hi @a-cordier - is this good to be merged please?
cc @phiz71

2022-11-09 15:21 UTC, merged