am: add doc regarding Passwordless remember device option
gravitee-io/gravitee-docs pull request #859
Opened 2022-10-03 12:12 UTC by tcompiegne

closes gravitee-io/issues#8506

2022-10-03 12:52 UTC, ivan-gravitee requested changes

2022-10-03 12:52 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/passwordless/user-guide-passwordless.adoc
> +the passwordless login page the next time a user wants to sign-in.
```suggestion
the passwordless login page the next time a user wants to sign in.
```

2022-10-03 12:52 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/passwordless/user-guide-passwordless.adoc
> +To improve user experience, AM can determine if a passwordless device is already enrolled or not for a user and decide to prompt directly
```suggestion
To improve user experience, AM can determine if a passwordless device is already enrolled (or not) for a user, and decide to prompt directly
```

2022-10-03 12:52 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/passwordless/user-guide-passwordless.adoc
> +NOTE: This option has been based where users always use the same browser and have one mobile and one laptop/desktop computer.
This is a bit unclear

2022-10-04 08:44 UTC, tcompiegne commented on pages/am/3.x/user-guide/passwordless/user-guide-passwordless.adoc
> +NOTE: This option has been based where users always use the same browser and have one mobile and one laptop/desktop computer.
Remove as it was unclear

2022-10-04 08:44 UTC, tcompiegne commented on pages/am/3.x/user-guide/passwordless/user-guide-passwordless.adoc
> +To improve user experience, AM can determine if a passwordless device is already enrolled or not for a user and decide to prompt directly
Force pushed

2022-10-04 08:44 UTC, tcompiegne commented on pages/am/3.x/user-guide/passwordless/user-guide-passwordless.adoc
> +the passwordless login page the next time a user wants to sign-in.
Force pushed

2022-10-04 09:29 UTC, ivan-gravitee approved these changes
LGTM

2022-10-04 10:58 UTC, leleueri approved these changes

2022-10-06 07:33 UTC, merged