Issues/#8454 document theme builder am
gravitee-io/gravitee-docs pull request #861
Opened 2022-10-04 09:29 UTC by tcompiegne

closes https://github.com/gravitee-io/issues/issues/8454 and closes https://github.com/gravitee-io/issues/issues/8477 and closes https://github.com/gravitee-io/issues/issues/8446

2022-10-04 14:50 UTC, ivan-gravitee requested changes
Looks great - I've added a few suggestions and edits.

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/breaking-changes/breaking-changes-3.19.adoc
> +For that reason the assets provided before AM 3.19 are now deprecated and will be removed in a future version.
```suggestion
Those assets are therefore deprecated and will be removed in a future version, as per the list below.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +AM is aiming to support multiple languages for the end user convenience.
```suggestion
AM supports internationalization in multiple languages so that end users can benefit from a great user experience.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +The internationalization option is available under domain `*Design -> Texts*` section
```suggestion
The internationalization option is available under the domain `*Design -> Texts*` section.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +NOTE: Under the hood all the templates uses Thymeleaf and Freemarker engines to support translation.
```suggestion
NOTE: Under the hood, all templates use Thymeleaf and Freemarker engines to support translation.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +NOTE: *3.19.0* release supports English and French language out of the box.
```suggestion
NOTE: The *3.19.0* release supports English and French languages out of the box.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +To create a new language or customise texts for a default supported languages:
```suggestion
To create a new language or customize texts for a default supported language:
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +. Click `*ADD A NEW LANGUAGE*` button in the `*Languages*` section
```suggestion
. Click `*ADD A NEW LANGUAGE*` button in the `*Languages*` section.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +. Select a language code from the drop-down menue and click `*ADD*` button.
```suggestion
. Select a language code from the dropdown menu and click the `*ADD*` button.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +. Click `*SAVE CHANGES*` button.
```suggestion
. Click the `*SAVE CHANGES*` button.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +. Select the language from the drop-down in the `*Translations*` section
```suggestion
. Select the language from the dropdown menu in the `*Translations*` section.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +. Click `*ADD A NEW TRANSLATION*`
```suggestion
. Click `*ADD A NEW TRANSLATION*`.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +. Provide a valid property key name and value you want to customise
```suggestion
. Provide a valid property key name and value that you want to customize.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +. Click `*ADD*` and then `*SAVE CHANGES*`
```suggestion
. Click `*ADD*` and then `*SAVE CHANGES*`.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +NOTE: The change should be immediately viewable in the `*Theme*` preview section for the template.
```suggestion
NOTE: You should be able to view the change immediately in the `*Theme*` preview section for the template.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +* Default locale is based on user web browser, the requested language cannot be overridden with query param such as *ui_locales*.
```suggestion
* The default locale is based on the end user's web browser - the requested language cannot be overridden with a query parameter such as *ui_locales*.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +== Out of the box translated properties
```suggestion
== Out-of-the-box translated properties
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +Default forms and email templates contain a set of translated properties which are listed below.
```suggestion
The default forms and email templates contain a set of translated properties, which are listed below.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +NOTE: For example, if you want to support Spanish language and translate the Login page title,
```suggestion
NOTE: For example, if you want to support Spanish and translate the Login page title,
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +Theme builder helps to create unique look and feel for the AM templates to achieve brand requirements according to your need.
```suggestion
The Theme Builder enables you to create a unique look and feel for your AM templates so they are aligned with your brand requirements.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +Theme builder makes it easier to add custom CSS, organization's logo in the templates and preview the changes all in one place.
```suggestion
The Theme Builder makes it easier to add custom CSS and the organization's logo in the templates, and to preview the changes - all in one place.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +Theme builder is available in the domain `*Design*` section. Here is a brief summary of the builder itself:
```suggestion
The Theme Builder is available in the domain `*Design*` section. A brief description of the builder follows below:
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +* The `*Settings*` consists of the following sections:
```suggestion
* The `*Settings*` include the following sections:
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +    ** `*General*`: inputs for logo, favicon URL and theme color palette
```suggestion
    ** `*General*`: inputs for logo, favicon URL, and theme color palette.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +    ** `*Custom CSS*`: place to write css for more advanced user
```suggestion
    ** `*Custom CSS*`: a place to add custom CSS (suitable for more advanced users).
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +* The `*Preview*` section, right-hand side of the `*Settings*` which let you switch between preview and HTML mode for more advanced customizati
```suggestion
* The `*Preview*` section on the right-hand side of `*Settings*` lets you switch between preview mode and HTML mode - suitable for more advanced customizations.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +* `*PUBLISH*` button: saves custom theme and templates
```suggestion
* `*PUBLISH*` button: saves the custom theme and templates.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +* `*RESET THE THEME*` button: delete the custom theme settings and reset the to the default theme
```suggestion
* `*RESET THE THEME*` button: deletes the custom theme settings and resets the builder to the default theme.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +== Update brand logo and theme color
```suggestion
== Updating the brand logo and the theme color
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +Updating brand logo and theme color is straight forward and the changes are immediately visible in the preview section.
```suggestion
It is straightforward to update the brand logo and the theme color. All changes are immediately visible in the preview section.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +NOTE: Logo, favicon and theme color are applied for all the default pages provided by AM.
```suggestion
NOTE: Logo, favicon, and theme color are applied for all the default pages provided by AM.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +If you want to customize a specific page, you have to select your page and switch to the HTML mode to enable and publish custom HTML templates.
```suggestion
If you want to customize a specific page, you must select your page and switch to the HTML mode to enable and publish custom HTML templates - for example, if third-party logo URLs have been used for logo and favicon and a theme color has been selected to preview the login page.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +As an example; 3rd party logo URLs have been used for logo and favicon and a theme color has been selected to preview the login page.
```suggestion

```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +NOTE: The content Security Policy (CSP) will prevent  3rd party URL access unless it is permitted.
```suggestion
NOTE: The content Security Policy (CSP) will prevent third-party URL access unless it has been set as permitted.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +For more information to allow cross domain URL access please check:
```suggestion
For more information on how to allow cross-domain URL access, please see 
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +link:{{ '/am/current//am_installguide_helm_prod_deployment.html' | relative_url }}[Mitigate XSS CSF in Helm^]
```suggestion
link:{{ '/am/current//am_installguide_helm_prod_deployment.html' | relative_url }}[Mitigate XSS CSF in Helm^].
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +Customising CSS is an option for more advanced user who wants more granular custom look and feel for the html forms.
```suggestion
Customising CSS is an option for more advanced users who want a more granular custom look and feel for the HTML forms.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +Custom CSS should be added as shown below. Any change should be viewable in the preview section instantly.
```suggestion
To add custom CSS, follow the example below. All changes will be instantly viewable in the preview section.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +Check the link below for all the available CSS properties and their default values.
```suggestion
Check the following documentation for information about all available CSS properties and their default values.
```

2022-10-04 14:50 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/expression-language/user-guide-expression-language.adoc
> +NOTE: As you may have noticed, `claims` and `additionalInformation` contain the same data. According to the place where the Expression Language is defined, the `claims` attribute may not be accessibl
```suggestion
NOTE: As you may have noticed, `claims` and `additionalInformation` contain the same data. Depending on the place where the Expression Language is defined, the `claims` attribute may not be accessible whereas the `additionalInformation` attribute will always be present.
```

2022-10-04 19:46 UTC, tcompiegne commented on pages/am/3.x/breaking-changes/breaking-changes-3.19.adoc
> +Starting from the version 3.19.0, the **use the migration guide available link:{{ '/am/current/am_userguide_branding_theme_builder.html' | relative_url }}[theme builder]** has been introduce to creat
Force pushed

2022-10-04 19:46 UTC, tcompiegne commented on pages/am/3.x/breaking-changes/breaking-changes-3.19.adoc
> +Starting from the version 3.19.0, the **use the migration guide available link:{{ '/am/current/am_userguide_branding_theme_builder.html' | relative_url }}[theme builder]** has been introduce to creat
Force pushed

2022-10-04 19:46 UTC, tcompiegne commented on pages/am/3.x/breaking-changes/breaking-changes-3.19.adoc
> +For that reason the assets provided before AM 3.19 are now deprecated and will be removed in a future version.
Force pushed

2022-10-04 19:47 UTC, tcompiegne commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +The internationalization option is available under domain `*Design -> Texts*` section
Force pushed

2022-10-04 19:47 UTC, tcompiegne commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +link:{{ '/am/current//am_installguide_helm_prod_deployment.html' | relative_url }}[Mitigate XSS CSF in Helm^]
Force pushed

2022-10-04 19:48 UTC, tcompiegne commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +Customising CSS is an option for more advanced user who wants more granular custom look and feel for the html forms.
Force pushed

2022-10-04 19:48 UTC, tcompiegne commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +Custom CSS should be added as shown below. Any change should be viewable in the preview section instantly.
Force pushed

2022-10-04 19:49 UTC, tcompiegne commented on pages/am/3.x/user-guide/branding/user-guide-branding-theme-builder.adoc
> +Check the link below for all the available CSS properties and their default values.
Force pushed

2022-10-04 19:49 UTC, tcompiegne commented on pages/am/3.x/user-guide/expression-language/user-guide-expression-language.adoc
> +NOTE: As you may have noticed, `claims` and `additionalInformation` contain the same data. According to the place where the Expression Language is defined, the `claims` attribute may not be accessibl
Force pushed

2022-10-09 23:51 UTC, ivan-gravitee requested changes
Some of the edits from the previous review are still pending - @tcompiegne can you have another look please?

2022-10-09 23:51 UTC, ivan-gravitee commented on pages/am/3.x/user-guide/branding/user-guide-branding-internationalization.adoc
> +AM is aiming to support multiple languages for the end user convenience.
AM supports internationalization in multiple languages so that end users can benefit from a great user experience.

2022-10-12 07:08 UTC, merged